### ISSUE TITLE
Build InfluxDB Dashboard

### ISSUE THREAD

**Issue by pjayathissa** [pjayathissa/cozie-covid#9]
Build a small influxdb dashboard that can show a few users for presentation purposes

**Comment by FedericoTartarini** [comment]
I have created one here [using codelab](https://colab.research.google.com/drive/1B7hN57WoD0TVtfVsY9O6aJ0HmISQ_DeY). You will need to specify userID and password for Influx

**Comment by pjayathissa** [comment]
Nice!
